# Generated by Django 3.1.2 on 2020-10-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('confirm_password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'registeration',
            },
        ),
    ]
