# Generated by Django 3.1.2 on 2020-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_remove_registeration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='name',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
