# Generated by Django 3.1.2 on 2020-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0004_registeration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerNo', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=400)),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'CustomerTable',
            },
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=300)),
                ('Color', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
            ],
            options={
                'db_table': 'ProductTable',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('OpeningTime', models.TimeField()),
                ('ClosingTime', models.TimeField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Showroom',
            },
        ),
    ]
