# Generated by Django 3.1.2 on 2020-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0005_customertable_producttable_showroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registeration',
        ),
        migrations.AddField(
            model_name='logintable',
            name='confirm_password',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logintable',
            name='name',
            field=models.CharField(default=1111, max_length=300),
            preserve_default=False,
        ),
    ]
