# Generated by Django 3.1.2 on 2020-11-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0006_auto_20201030_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='ClosingTime',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='OpeningTime',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='phone',
            field=models.CharField(max_length=300),
        ),
    ]
