# Generated by Django 3.1.2 on 2020-11-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0007_auto_20201103_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='Phone',
            field=models.CharField(max_length=400),
        ),
    ]
