# Generated by Django 3.1.2 on 2020-11-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0008_auto_20201103_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='type',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroom',
            name='type',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
