# Generated by Django 3.1.2 on 2020-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0009_auto_20201105_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='type',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
