# Generated by Django 3.1.2 on 2020-11-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0010_logintable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='password',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroom',
            name='password',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
