# Generated by Django 3.1.2 on 2020-11-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0011_auto_20201105_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertable',
            old_name='CustomerName',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='type',
        ),
    ]
