# Generated by Django 3.1.2 on 2020-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0012_auto_20201105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='type',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
