# Generated by Django 3.1.2 on 2020-11-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0013_logintable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_no', models.IntegerField()),
                ('category_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
