# Generated by Django 3.1.2 on 2020-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='category_name',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.ImageField(default='old', upload_to=''),
            preserve_default=False,
        ),
    ]
