# Generated by Django 3.1.2 on 2020-11-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0015_auto_20201109_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttable',
            name='image',
        ),
    ]
