# Generated by Django 3.1.2 on 2020-11-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0016_remove_producttable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.ImageField(default=11, upload_to=''),
            preserve_default=False,
        ),
    ]
