# Generated by Django 3.1.2 on 2020-11-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0018_remove_producttable_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTable',
        ),
    ]
