# Generated by Django 3.1.2 on 2020-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0019_delete_producttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=300)),
                ('Color', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
                ('category_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'ProductTable',
            },
        ),
    ]
