# Generated by Django 3.1.2 on 2020-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0020_producttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='username',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
