# Generated by Django 3.1.2 on 2020-11-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0021_producttable_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='username',
            new_name='sname',
        ),
    ]
