# Generated by Django 3.1.2 on 2020-11-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0023_auto_20201111_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
