# Generated by Django 3.1.2 on 2020-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0024_auto_20201111_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=11, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
