# Generated by Django 3.1.2 on 2020-11-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0025_auto_20201111_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
