# Generated by Django 3.1.2 on 2020-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0027_customerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
