# Generated by Django 3.1.2 on 2020-11-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0029_auto_20201114_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='updated',
        ),
    ]
