# Generated by Django 3.1.2 on 2020-11-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0030_remove_customerfeedback_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFeedBack',
        ),
    ]
